import { Logo } from "@/types";
import { v4 as uuidv4 } from "uuid";

export const logo: Logo = {
  html: {
    key: uuidv4(),
    width: 300,
    height: 341,
    src: "https://res.cloudinary.com/dsgtmtcmt/image/upload/v1751369440/html5_gv9p33.webp",
    alt: "HTML5",
  },
  css: {
    key: uuidv4(),
    width: 300,
    height: 342,
    src: "https://res.cloudinary.com/dsgtmtcmt/image/upload/v1751369441/css3_tyt57e.webp",
    alt: "CSS3",
  },
  javascript: {
    key: uuidv4(),
    width: 300,
    height: 300,
    src: "https://res.cloudinary.com/dsgtmtcmt/image/upload/v1751369440/javascript_v0lom8.webp",
    alt: "JavaScript",
  },
  typescript: {
    key: uuidv4(),
    width: 256,
    height: 256,
    src: "https://res.cloudinary.com/dsgtmtcmt/image/upload/v1751369442/ts-logo-256_nddqfv.svg",
    alt: "TypeScript",
  },
  sass: {
    key: uuidv4(),
    width: 300,
    height: 300,
    src: "https://res.cloudinary.com/dsgtmtcmt/image/upload/v1751700075/sass_fwdyru.webp",
    alt: "SASS",
  },
  react: {
    key: uuidv4(),
    width: 569,
    height: 512,
    src: "https://res.cloudinary.com/dsgtmtcmt/image/upload/v1751351667/react_dark_mmzyxn.svg",
    alt: "React",
  },
  nextjs: {
    key: uuidv4(),
    width: 800,
    height: 800,
    src: "https://res.cloudinary.com/dsgtmtcmt/image/upload/v1751370505/nextjs_i4oypf.svg",
    alt: "Next.js",
  },
  nodejs: {
    key: uuidv4(),
    width: 300,
    height: 300,
    src: "https://res.cloudinary.com/dsgtmtcmt/image/upload/v1751369438/node-js_jafvrd.webp",
    alt: "Node.js",
  },
  express: {
    key: uuidv4(),
    width: 300,
    height: 162,
    src: "https://res.cloudinary.com/dsgtmtcmt/image/upload/v1751699904/express-js_alntqc.webp",
    alt: "Express",
  },
  mongodb: {
    key: uuidv4(),
    width: 300,
    height: 300,
    src: "https://res.cloudinary.com/dsgtmtcmt/image/upload/v1751699178/MongoDB_xvql3f.webp",
    alt: "MongoDB",
  },
  sqlite: {
    key: uuidv4(),
    width: 300,
    height: 300,
    src: "https://res.cloudinary.com/dsgtmtcmt/image/upload/v1751369443/sql_tu1clx.webp",
    alt: "SQLite",
  },
  chakraUI: {
    key: uuidv4(),
    width: 300,
    height: 314,
    src: "https://res.cloudinary.com/dsgtmtcmt/image/upload/v1751371291/chakra-ui_cxqioz.svg",
    alt: "Chakra UI",
  },
  tailwindcss: {
    key: uuidv4(),
    width: 300,
    height: 180,
    src: "https://res.cloudinary.com/dsgtmtcmt/image/upload/v1751369437/tailwind-css_kcbosg.webp",
    alt: "Tailwind CSS",
  },
  figma: {
    key: uuidv4(),
    width: 300,
    height: 450,
    src: "https://res.cloudinary.com/dsgtmtcmt/image/upload/v1751371417/figma_mod6xa.svg",
    alt: "Figma",
  },
  photoshop: {
    key: uuidv4(),
    width: 300,
    height: 292,
    src: "https://res.cloudinary.com/dsgtmtcmt/image/upload/v1751700559/photoshop_xrpcqq.webp",
    alt: "Photoshop",
  },
  illustrator: {
    key: uuidv4(),
    width: 300,
    height: 292,
    src: "https://res.cloudinary.com/dsgtmtcmt/image/upload/v1751700558/illustrator_jibd6n.webp",
    alt: "Illustrator",
  },
};
